title: "Maheshkumar Paulraj"
description: "IAM Professional | Identity Lifecycle | Active Directory | Cloud IAM"
theme: jekyll-theme-slate

# Optional but recommended:
markdown: kramdown
highlighter: rouge

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
